### ISSUE TITLE
MacOS python run auto terminates after 15 seconds of starting

### ISSUE THREAD

**Issue by jckozy86** [nyu-mlab/iot-inspector-client#115]
Followed instructions from website:
https://inspector.engineering.nyu.edu/site/post/getting-started/#i-class-fab-fa-apple-i-macos-download

no errors during install, no errors during start up.
post running: `python3 start_inspector.py` a webpage opened up[https://dashboard.iotinspector.org/dashboard]( https://dashboard.iotinspector.org/dashboard)
Tried hitting rescan network and traversed the UI when the webpage opened up but it still auto terminates

terminal initially shows:
```
======================================
Princeton IoT Inspector for Windows 10
======================================

Running on IP Address: 10.0.0.28

We have also opened a new browser window for you to view the IoT Inspector report. If you don't see a new browser window, use the following private link:

https://dashboard.iotinspector.org/user/PakP-KFQt-85AY-8b46

To stop IoT Inspector, simply close this window or hit Control + C.

Questions? Email us at iot-inspector@lists.cs.princeton.edu.

```

and after 15 seconds (with no errors showing on the terminal) It starts a countdown and shows below

```
Cleaning up (10)...
Cleaning up (9)...
Cleaning up (8)...
Cleaning up (7)...
Cleaning up (6)...
Cleaning up (5)...
Cleaning up (4)...
Cleaning up (3)...
Cleaning up (2)...
Cleaning up (1)...
net.inet.ip.forwarding: 1 -> 0

        Princeton IoT Inspector has terminated.

        Feel free to close this window.
```

MacOS Monterey v12.2.1
using brew, zsh and iterm2
Chrome Browser

HTTPS everywhere was disabled ( saw this suggestion from  #3 )  and also disabled uBlock origin and Ghostery

**Comment by dbl001** [comment]
What's in the log file?
E.g. - /var/root/princeton-iot-inspector/iot_inspector_logs.txt

**Comment by crazyideas21** [comment]
Not really sure why the client would terminate prematurely. We're currently working on the next version (to be released May-ish) that would not have this issue. 

The log file records what devices are being inspected and what data is being shared with the cloud. Mostly for debugging purposes.

**Comment by crazyideas21** [comment]
The next release has a completely different architecture that wouldn't have this problem (per @jckozy86).

**Comment by nicholasphair** [comment]
I was able to reproduce this issue and traced it to `self.last_ui_contact_ts` not being updated. #117 proposes a fix by ripping out the check for `self.last_ui_contact_ts`. 

My assumption was that https://github.com/nyu-mlab/iot-inspector-client/blob/92b422e3b74b3b0937ed3ce542509f6513e38ba6/src/data_upload.py#L55-L63 is just not suppose to be there. In fact, even the comment doesn't line up. It seems to go with the next code block :)
