### ISSUE TITLE
Ubuntu 20.04 scapy build failure

### ISSUE THREAD

**Issue by larrym** [nyu-mlab/iot-inspector-client#120]
On running `pip install -r requirements.txt`, the following error occurred. Any way to correct this?

    ...
    Building wheels for collected packages: scapy
      Building wheel for scapy (setup.py) ... error
      ERROR: Command errored out with exit status 1:
       command: /home/larry/src/iot-inspector-client/src/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-he8mi2x5/scapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-he8mi2x5/scapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-36pyua0i
           cwd: /tmp/pip-install-he8mi2x5/scapy/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
  
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for scapy
      Running setup.py clean for scapy
    Failed to build scapy
    ...

**Comment by crazyideas21** [comment]
@william1357chen Are you able to replicate the issue on your Ubuntu 20 VM?

**Comment by larrym** [comment]
Running on metal, not VM.

**Comment by william1357chen** [comment]
Try to install wheel first with `pip install wheel` before installing scapy. Additionally, on Ubuntu you have to install scapy with the `apt` package manager instead of pip, so `sudo apt-get python3-scapy`.

**Comment by william1357chen** [comment]
If both these methods don’t work lmk.

**Comment by larrym** [comment]
I think it worked.

$ pip install wheel => (Requirement already satisfied: wheel in
> /usr/lib/python3/dist-packages (0.34.2))

$ sudo apt python3-scapy
> $ sudo apt install python3-scapy
> $ pip install -r requirements.txt
>

$ python3 start_inspector.py
> net.ipv4.ip_forward = 1
>

Forgive my ignorance. I watched Prof Huang's video presentation. After
starting the inspector, I expected to see more output, but there is only a
single line.

**Comment by william1357chen** [comment]
You are supposed to receive a URL to open inspector in the browser.

**Comment by larrym** [comment]
No. My previous message shows the output, a single line.

**Comment by william1357chen** [comment]
Can you check the logs at `~/princeton-iot-inspector/iot_inspector_logs.txt`? If you cannot find the logs there, it should be in the root folder because we use `sudo` to run Inspector, so:
```bash
$ sudo su
$ cd /root
```
You will find the `princeton-iot-inspector` folder in there.

**Comment by crazyideas21** [comment]
@larrym Try to run everything as root?
