### ISSUE TITLE
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH

### ISSUE THREAD

**Issue by AnthonyMastrean** [nyu-mlab/iot-inspector-client#13]
I'm getting this error on startup. Is `tcpdump` required or no? Is this error from your application or from a dependency?

```
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
```

If I add this to my system (or to the [install dependencies](https://github.com/noise-lab/iot-inspector-client/blob/master/linux-setup.sh#L5) script), the error goes away.

```
apt install tcpdump
```

---

I'm on Ubuntu 18.04 "bionic".

**Comment by SASA10333** [comment]
**did you fix it?**
