### ISSUE TITLE
Main network activity graph not showing device names

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#135]
The current network activity graph is showing device IDs

![Screen Shot 2022-07-06 at 13 38 40](https://user-images.githubusercontent.com/1479070/177610683-e24d1dce-964e-4898-88eb-d568ea5ca6fa.png)

Ideally, the fix should show device names instead (for devices that are named)

**Comment by crazyideas21** [comment]
Also, despite having more than 3 devices, the bar graph only shows 3 devices. Should we show all devices instead?

**Comment by cdnicoll** [comment]
1. Showing all devices is really cluttered and a bit of a performance hit. We're looking into showing all devices and filtering out those that are shown on the list below. I'll update you when we have a more clear solution. As for device name, 100% agree on that. We'll get that in there
2. The query is heavy, but we're also doing a bit of math on our side so the javascript is a bit slow. I think every minute should be okay... I'll try it out and see how it works

**Comment by crazyideas21** [comment]
Looks good to me for now. Thanks @cdnicoll!
