### ISSUE TITLE
Saved tags do not appear in the device list

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#136]
Users can save a tag for a device, but the device list doesn't show the tag.

For instance, I create a new tag `danny` and save it:
![Screen Shot 2022-07-06 at 13 46 33](https://user-images.githubusercontent.com/1479070/177611893-973dcbfa-635d-494d-a310-0cc9cd8f7af6.png)

However, the `danny` tag doesn't apppear in the main list:
![Screen Shot 2022-07-06 at 13 47 10](https://user-images.githubusercontent.com/1479070/177611998-45564583-37b8-470b-a867-c5d2ad0991ea.png)

Here's a video recording of the issue: https://www.loom.com/share/3c7db082294b407db5d931b5115ea668

**Comment by cdnicoll** [comment]
Fixed the in the latest PR: https://github.com/nyu-mlab/iot-inspector-client/pull/140

**Comment by crazyideas21** [comment]
Thanks!

**Comment by crazyideas21** [comment]
Somehow this issue reappeared. Are you able to reproduce this issue? 

https://www.loom.com/share/d6b0bf1379344c1bb50155c8c542acf2

I'm using the front end with real data from my home network.

**Comment by cdnicoll** [comment]
fix in latest PR https://github.com/nyu-mlab/iot-inspector-client/pull/155

**Comment by crazyideas21** [comment]
Confirmed. Thanks!
