### ISSUE TITLE
Single Row Generated for User Configs

### ISSUE THREAD

**Issue by cdnicoll** [nyu-mlab/iot-inspector-client#142]
Hey @crazyideas21 I've gone ahead and created a table for user_configs. ( see here https://github.com/nyu-mlab/iot-inspector-client/commit/a3514915e520145d5b2afb06cf482bad2258916e)

The idea is that it will contain a single row within id `0`. Could you have it so that when spinning up the mock database it'll create the single row. If the database already exists, it shouldn't overwrite that row.

Is that something that can be done?
Thanks!

**Comment by crazyideas21** [comment]
> Is that something that can be done?

Yes.

> do we want consent etc to be persistent after the server shuts down?

Yes.

> I could also set this up on server startup, so each time the user sets up the server a user role will be created for them.

I can do that on my end in both the mock script and in the Python driver. Will push an update today. (Sorry been fighting a fire elsewhere.)

**Comment by cdnicoll** [comment]
No worries Danny! That sounds great. Let me know if I can help with anything else!

**Comment by crazyideas21** [comment]
Pushed. By the way, I removed AUTOINCREMENT because it is unncessary; see https://www.sqlite.org/autoinc.html
