### ISSUE TITLE
Iot-inspector windows not working.

### ISSUE THREAD

**Issue by amaczen** [nyu-mlab/iot-inspector-client#146]
After running the start_inspector.bat, The CLI displays there was an error downloaidng the latest Iot Inspector. The same error occurs across different windows machines.
[
![error](https://user-images.githubusercontent.com/29413269/184355788-802ab1ff-1ddf-46da-acdc-83bbf8ca6d6a.png)
](url)

**Comment by crazyideas21** [comment]
As we're preparing for a relaunch, the current infrastructure is unstable. See https://iotinspector.org/
