### ISSUE TITLE
Unable to change device name

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#151]
If I change the name of a device and refresh the device's page, the device's name is not updated. Also, the updated name is not shown on the main dashboard. There's an occasional blank screen, too.

See this video for details.

https://www.loom.com/share/be5aea57149e4f40b2fa69e4968fd467

I'm using the front end with real data from my home network.

**Comment by cdnicoll** [comment]
fix in latest PR https://github.com/nyu-mlab/iot-inspector-client/pull/155

**Comment by crazyideas21** [comment]
I can confirm that I can save the device name and tag, but I cannot save the device vendor.

See a demo video here: https://www.loom.com/share/3735f2c05e0d4baca27d6a43c3ea6a87

Note that this is a clean install with mock data. I started the UI with `yarn install:all; yarn prisma:generate`, followed by `yarn start`.

Could you look into this, please @cdnicoll ?

**Comment by cdnicoll** [comment]
@crazyideas21 should be fixed with this PR: https://github.com/nyu-mlab/iot-inspector-client/pull/160

**Comment by crazyideas21** [comment]
Confirmed. Thank you!
