### ISSUE TITLE
Network Activity Graph shows all 177 bytes

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#152]
I'm seeing 177 bytes in all the boxes when I'm running Inspector on my actual home network.

<img width="1000" alt="Screen Shot 2022-11-30 at 00 43 45" src="https://user-images.githubusercontent.com/1479070/204717228-3f94cb0d-a8bb-4341-993c-d48fe2091a0e.png">

Certainly not a coincidence that all the boxes are 177 🙃

**Comment by cdnicoll** [comment]
hey @crazyideas21 This is the only issue I can't provide much insight into until I can spin up the device monitoring app. For now I'll block this issue, but when it's ready for me to dig into I'll hop into it.

**Comment by crazyideas21** [comment]
@cdnicoll Try these instructions ("For All Developers" section)?

https://github.com/nyu-mlab/iot-inspector-client/tree/cr-dev#for-all-developers

When you run the frontend, make sure to use `sudo yarn`, as the database files will be created with `root`.

Let me know how that works?

**Comment by crazyideas21** [comment]
@cdnicoll FYI, the internal release is out. M1 chip for now.

**Comment by cdnicoll** [comment]
Hey @crazyideas21 is this still occurring?

**Comment by crazyideas21** [comment]
>Hey @crazyideas21 is this still occurring?

Yes, @cdnicoll 

Here's a screenshot that I took a few minutes ago, based on a fresh install:

This is the overview:
![Screen Shot 2023-01-11 at 18 24 17](https://user-images.githubusercontent.com/1479070/211939596-0ed17a36-6f52-46b6-a16b-8df4a76df3b7.png)

Notice how device `99d` has 177 bytes.

We see the same number when I view the details for device `99d`
![Screen Shot 2023-01-11 at 18 24 24](https://user-images.githubusercontent.com/1479070/211939660-2507157a-7174-4590-9099-220ff4baaeae.png)

**Comment by crazyideas21** [comment]
Try running Inspector on your computer? The current alpha build of Inspector works on both Intel and M1 based macOS in theory.
