### ISSUE TITLE
Clicking the title always brings me back to consent screen

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#153]
If I click on the Home Data Inspector title icon, I'm always taken back to the consent screen, even though I have previously consented.

See video https://www.loom.com/share/eec849fb316b4fc5994453e77c976af8

**Comment by cdnicoll** [comment]
We've fixed this, i've pr'd the change into your repo

**Comment by cdnicoll** [comment]
https://github.com/nyu-mlab/iot-inspector-client/pull/154

**Comment by crazyideas21** [comment]
Confirmed. Thanks!
