### ISSUE TITLE
sqlite db files need to be located where both UI and Driver can find

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#162]
Right now the sqlite db files are located in relative directories in the source code, but in deployment these relative directory structure will not exist. The db files should be referenced with absolute directories, as least for the initial macOS build.

**Comment by crazyideas21** [comment]
Committed a fix that would work for macOS for now.

**Comment by crazyideas21** [comment]
cc: @cdnicoll The sqlite db files are located at `/Applications/inspector/` for now. Assumes macOS build. See the [diff](https://github.com/nyu-mlab/iot-inspector-client/commit/1f927e4a724c8bcb61ff61f39049aa518183927a)

**Comment by cdnicoll** [comment]
@crazyideas21 Im getting errors around this. Looking in your repo I don't see the `/Applications` directory

**Comment by crazyideas21** [comment]
I've updated the README (https://github.com/nyu-mlab/iot-inspector-client/commit/0d138022d510392b05d000cfad51a80d658931a4) with new instructions. The main gist is that all the database files are located in `/Applications/inspector` now. Make sure to run Inspector and `yarn dev` with sudo. Let me know if this works, @cdnicoll

**Comment by crazyideas21** [comment]
Just to add, the main Inspector Python driver creates and references db files in `/Applications/inspector`. Same as the `generate_mock_data.py` script.

I've updated the prisma schema files to reference the new directory as well. See [commit](https://github.com/nyu-mlab/iot-inspector-client/commit/1f927e4a724c8bcb61ff61f39049aa518183927a).

**Comment by crazyideas21** [comment]
@cdnicoll Are you able to get this resolved?
