### ISSUE TITLE
multiprocessing doesn't play well with pyinstaller

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#166]
When Inspector is frozen with pyinstaller and executed from the frozen package, multiple instances are running and writing to the DB at the same time, despite having turned on the `freeze_support` flag: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by crazyideas21** [comment]
@viz-prakash i have to disable multiprocessing for now. for the actual user deployment, it's okay if we're missing packets (but not for our in-lab setups). we'll probably use coroutines to fix this later.

**Comment by viz-prakash** [comment]
Sounds good.
