### ISSUE TITLE
need a transparenct png icon

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#173]
@cdnicoll Can you and your team provide a transparent png to serve as Inspector's status bar icon?

**Comment by crazyideas21** [comment]
Looks ugly now; see https://github.com/nyu-mlab/iot-inspector-client/issues/171#issuecomment-1367439225

**Comment by cdnicoll** [comment]
@crazyideas21 Attached here:

![image](https://user-images.githubusercontent.com/245761/210621064-5336415c-d694-4752-97ad-65c3bf1a357f.png)

**Comment by crazyideas21** [comment]
thanks @cdnicoll

**Comment by crazyideas21** [comment]
Doesn't look good in dark mode though. My bad about transparent icon :(

![Screen Shot 2023-01-05 at 12 49 38](https://user-images.githubusercontent.com/1479070/210851251-f243c104-2f3f-4d16-9361-a8f1fa63cc08.png)

Ideally, an icon that looks like this https://github.com/nyu-mlab/iot-inspector-client/issues/171#issuecomment-1367439225 (which is ugly with the rectangular borders), but with a round/circular border. Inside the border, the background is white. Just an idea. Let's mark this as open for now.
