### ISSUE TITLE
Device name not updated

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#180]
After I renamed a device, the new name is shown in the bar chart on the dashboard, but not in the section that shows data consumption per device.

For example, I renamed a device as "Fire TV". This update is reflected on the bar chart below, but the old name is still in the data consumption section (see red circles):

![Screen Shot 2023-01-05 at 10 48 43](https://user-images.githubusercontent.com/1479070/210822887-5b791270-4519-4fb7-bed7-e97990f0cf10.png)

**Comment by cdnicoll** [comment]
@crazyideas21. Thanks for flagging, this has been resolved in latest commit.

https://github.com/nyu-mlab/iot-inspector-client/pull/181

**Comment by crazyideas21** [comment]
Thanks @cdnicoll
