### ISSUE TITLE
You need Other in the pulldown menu for Device Tags

### ISSUE THREAD

**Issue by stevegoldfield** [nyu-mlab/iot-inspector-client#183]
The first connected device I looked at was my solar inverter, which connects to the internet to report on the health of my solar system. I have another device which does the same thing. So, either there should be an Other option or else you will need to add these (Solar device) as they come up. Even better would be to allow the user to create a new device tag.

**Comment by stevegoldfield** [comment]
The second device I looked at is my second router. Again, I don't see a tag for it.

**Comment by stevegoldfield** [comment]
Next problem is that I get an error message when I try to save the device details.

**Comment by stevegoldfield** [comment]
No entry on the list for a smartphone.

**Comment by crazyideas21** [comment]
Could you send a few screenshots to illustrate the problem? Thanks!
