### ISSUE TITLE
yarn install:all failure

### ISSUE THREAD

**Issue by gitmichaelo** [nyu-mlab/iot-inspector-client#185]
The install seemed to finish ok but when the IoT Inspector was stated for the first time (automatically via the install process) an error occurred - "Failed to do yarn install:all." The inspector_test never finished.
Running macOS Big Sur, version 11.4

[init.log](https://github.com/nyu-mlab/iot-inspector-client/files/10386686/init.log)
[inspector.log](https://github.com/nyu-mlab/iot-inspector-client/files/10386688/inspector.log)
<img width="540" alt="Screen Shot 2023-01-10 at 12 27 50 PM" src="https://user-images.githubusercontent.com/65247211/211658643-7f1d2292-f155-4d2e-8d1c-593157e7dab1.png">

**Comment by LookToLuke** [comment]
I'm getting this error as well.

**Comment by crazyideas21** [comment]
@cdnicoll Here's a log snippet from another user with a similar failure while doing `yarn install:all`:

```
error concurrently@7.2.1: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.0 || >=16.0.0". Got "10.6.0"
```

**Comment by cdnicoll** [comment]
Looks like a node versioning issue. I'll take a look into it. May reach out with some questions on the build process

**Comment by crazyideas21** [comment]
FYI @cdnicoll @tbeck Here's the script that sets up the UI, which first installs the latest nodejs, installs yarn, and does `yarn install:all`.

**Comment by crazyideas21** [comment]
cc: @Rapoda

**Comment by wwwiiilll** [comment]
I think the issue relates to this check here in the install script which is only verifying if `npm` is installed but doesn't verify the node version itself. 
``` echo "Checking npm version"
    npm --version

    # Install npm if not
    if [ $? -ne 0 ];```

If npm isn't installed then node 18 is installed which meets the `concurrently@7.2.1` engine requirements but for anyone who already has an older version of node installed this satisfies the npm check but it is a few minor versions behind, hence they're running into this issue.
 
Is it worth changing the script to instead check if the node version is 18 (current lts) and if it's an older version then upgrade it as if node wasn't installed? (Alternatively anyone who is running into this issue should be able to update to their latest minor version of node locally before installing and that will also resolve this for anyone on Node 12+)

Something like below (courtesy of ChatGPT) should work
````NODE_VERSION=$(node -v | awk -Fv '{print $2}')
IFS=. read -ra version_array <<< "$NODE_VERSION"

if [ "${version_array[0]}" -ge 18 ]; then
#continue install here```

**Comment by crazyideas21** [comment]
I'll look into this. Thanks for the suggestion @wwwiiilll !
