### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by JohnDdoo** [nyu-mlab/iot-inspector-client#186]
Installing on a 2015 MacBook Pro running Monterey 12.6.2. When I clicked on the zip file, I got 2 files, inspector_test.app & inspector_test 2.app (I followed the instructions explicitly). I clicked on the first one, and it started to install, but quickly got the error msg “Python drive failed to install”. I quit, tried again, same message. I stopped, tried the _2 file & got the same error message. I cannot copy/paste the relevant files from my MBP to this message on my iPad, but will try to do so from the MBP in a separate message. Thanks

**Comment by crazyideas21** [comment]
Got it. Please upload your log files per #187
