### ISSUE TITLE
python driver fails to start

### ISSUE THREAD

**Issue by JohnDdoo** [nyu-mlab/iot-inspector-client#187]
Here is the downloaded file that failed to install the inspector, freezing at installing the Python drive on several occasions.

[inspector_test.app.zip](https://github.com/nyu-mlab/iot-inspector-client/files/10387694/inspector_test.app.zip)

GitHub will not allow me to upload the .app files, but here's a screenshot of my downloads folder:
<img width="599" alt="Screen Shot 2023-01-10 at 6 13 57 PM" src="https://user-images.githubusercontent.com/122412417/211688583-a39ce360-c2e0-48ff-ab7d-5defaab0a950.png">

**Comment by crazyideas21** [comment]
Could you send me `init.log`? You can find the instructions in [the "Report Problems" section](https://github.com/nyu-mlab/iot-inspector-client/releases/tag/v2.0.0-alpha).

**Comment by JohnDdoo** [comment]
I am serving at our soup kitchen this morning, but will try to do this this afternoon. Sorry for the delay.BillOn Jan 11, 2023, at 9:42 AM, Danny Y. Huang ***@***.***> wrote:﻿
Could you send me init.log? You can find the instructions in the "Report Problems" section.

**Comment by patrickschmahl** [comment]
I don't have any init.log in my Inspector folder. My install never worked; I tried installing Python separately but I still get the Python failure error.
I'm running MacOS 10.11.6, if that helps.

**Comment by JohnDdoo** [comment]
[init.log](https://github.com/nyu-mlab/iot-inspector-client/files/10396674/init.log)
here's the init.log; i did a search on the hard drive and applications specifically & there's no inspector.log file found. Sorry to have been delayed in getting this out to you.
BD

**Comment by crazyideas21** [comment]
For everyone's reference, this is the relevant part of the log file about the error:

```
WARNING: This interface is not specified in any provider ! See conf.ifaces output
IoT Inspector cannot run on non-Ethernet network adapters, (e.g., VPN)
69:77: execution error: Can’t get application "chrome". (-1728)
For details, visit https://iotinspector.org/netmask-error/
```

@JohnDdoo This error occurred because you were using a VPN while running Inspector. It's a known issue that Inspector does not work when a VPN is running. Try disabling the VPN and see if Inspector works again? If not, send me the log file?

**Comment by crazyideas21** [comment]
> I don't have any init.log in my Inspector folder. My install never worked; I tried installing Python separately but I still get the Python failure error.
> I'm running MacOS 10.11.6, if that helps.

@patrickschmahl Can you take a screenshot of the /Applications/inspector/tmp folder? I'd expect `init.log` to be there, per this screenshot:

![image](https://user-images.githubusercontent.com/1479070/211941531-5c9a0490-2902-447b-b422-b0a44d0ff4ac.png)

Without `init.log`, it'd be very hard for me to pinpoint the issue.

**Comment by patrickschmahl** [comment]
Hi, here's the error I get:



And here's the Inspector folder...empty:




Patrick
 

    On Wednesday, January 11, 2023 at 06:44:04 PM EST, Danny Y. Huang ***@***.***> wrote:  
 
 



I don't have any init.log in my Inspector folder. My install never worked; I tried installing Python separately but I still get the Python failure error.
I'm running MacOS 10.11.6, if that helps.


@patrickschmahl Can you take a screenshot of the /Applications/inspector/tmp folder? I'd expect init.log to be there, per this screenshot:



Without init.log, it'd be very hard for me to pinpoint the issue.
