### ISSUE TITLE
couple of dialogs not mentioned in the readme

### ISSUE THREAD

**Issue by SirSpidey** [nyu-mlab/iot-inspector-client#189]
I got these 2 dialogs during installation. They're not listed in the installation part of the readme. They are not unusual dialogs, but installation should probably mention about allowing incoming network connections

![image](https://user-images.githubusercontent.com/8194208/211700833-d312b4a5-a18d-4be8-8064-643782d1a8b7.png)

![image](https://user-images.githubusercontent.com/8194208/211700856-6046e1c9-4fe2-4fe2-b01d-2d4adf499a77.png)

**Comment by crazyideas21** [comment]
Thanks! I've updated the README: https://github.com/nyu-mlab/iot-inspector-client/releases/tag/v2.0.0-alpha
