### ISSUE TITLE
Chart of network activity has weird timeline

### ISSUE THREAD

**Issue by SirSpidey** [nyu-mlab/iot-inspector-client#190]
I don't understand the timeline here. Left of chart is 8:59 PM. Right-most is 8:35 PM. In between has times after 9PM

Does this come from multiple instances or starting the app multiple times?

![image](https://user-images.githubusercontent.com/8194208/211704531-36e04078-daf1-4471-9a8d-e5971fb05605.png)

**Comment by crazyideas21** [comment]
@cdnicoll thoughts?

**Comment by cdnicoll** [comment]
@crazyideas21 thanks Danny. First glance might be sorting behaviour. Cc'ing @tbeck for visibility

**Comment by crazyideas21** [comment]
@cdnicoll @SirSpidey Looks like I encountered this issue as well; see this screenshot: https://github.com/nyu-mlab/iot-inspector-client/issues/152#issue-1469081368
