### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by jeffwachtel** [nyu-mlab/iot-inspector-client#191]
Couldn't complete installation. Requested files and 2 screenshots attached. 

Good luck!

[inspector.log](https://github.com/nyu-mlab/iot-inspector-client/files/10397150/inspector.log)
[init.log](https://github.com/nyu-mlab/iot-inspector-client/files/10397151/init.log)
<img width="431" alt="Screenshot 2023-01-11 at 4 58 34 PM" src="https://user-images.githubusercontent.com/40703734/211950607-82016d51-ce81-410f-8146-c7011e614fc3.png">
<img width="288" alt="Screenshot 2023-01-11 at 4 59 11 PM" src="https://user-images.githubusercontent.com/40703734/211950666-5562f48b-3157-4537-8fe6-8b7f1b58d49e.png">

**Comment by crazyideas21** [comment]
same issue as #185
