### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by wwwiiilll** [nyu-mlab/iot-inspector-client#192]
Following the [Run the Python Driver Guide](https://github.com/nyu-mlab/iot-inspector-client/tree/cr-dev#run-the-python-driver) on the cr-dev branch I run into this issue when running the final command

`FileNotFoundError:` [Errno 2] No such file or directory: 'oui.txt'`

If I change into the inspector dir before running the command then the driver starts as expected. 
Might be quick thing to update the readme to reflect this but want to make sure I didn't miss a step somewhere either.

**Comment by crazyideas21** [comment]
thanks for the comments! fixed
