### ISSUE TITLE
Clarify consequences and security risks of _installing_ iot-inspector-client

### ISSUE THREAD

**Issue by nealmcb** [nyu-mlab/iot-inspector-client#25]
IoT-inspector does not warn of the risks of _installing_ the tool prior to installation, and does not follow best practices for installation and client security.

The instructions should start by showing the disclaimer and warnings, so users know what they're getting in to before installing it. If, after learning of the risks, they aren't going to consent, it is a waste of time to install it, and might even cause the user various Python configuration and security problems, since the un-installation procetures don't remove everything that was installed.

E.g. the Linux installation scripts do not warn the user about what would seem to be a variety of security and system configuration risks:

* On the [download page](https://iot-inspector.princeton.edu/blog/post/getting-started/), instructions to click for doing the installation are placed above the material that people are warned to read before installation. The installation scripts themselves provide no warning. The app itself says simply `Please run as root` if not run with full system permissions. All these scripts should include links to clear warnings and ask the user for permission after they've read the warnings. 
* The Installation shell code is run as root, risking bugs or malicious code in the installer and in all the installers for all the third-party packages that are installed. The user should at least be warned to look at the code and package lists. Signatures for the code should be provided. This is a big and growing problem throughout the world of software development: [Malware in PyPI Code Shows Supply Chain Risks](https://www.darkreading.com/application-security/malware-in-pypi-code-shows-supply-chain-risks/d/d-id/1335310)
If even security tools don't help users learn good hygiene, where are they going to learn it?
* A variety of Python packages are installed as root into the system's Python2 library, rather than being installed via venv or into the individual user's Python package space. No provision is made for keeping these packages up-to-date, though bugs in them are likely to surface over time.
* The whole process runs as root. Normally daemon processes run only essential code as root, in order to minimize the attack surface, rather than opening up the whole system to any flaw in any of the project code or Python libraries.
* The [procedures to uninstall IoT Inspector](https://iot-inspector.princeton.edu/blog/post/faq/#how-do-i-delete-iot-inspector-from-my-computer) don't remove the Python packages that it installed. Using a Python virtual environment as noted above would make it easy to do a clean removal.
* The code is written in Python2. which will not have any security updates as of 2010-01-01, less than 3 months from now. See [Python 2 End Of Life Threatens Security](https://www.i-programmer.info/news/216-python/13045-python-2-end-of-life-threatens-security.html)

In addition, as noted in #21, the tool runs persistently, regardless of who is logged in, and thus may send information that others may find sensitive without warning them.

Finally, readers may be under the assumption, given the unqualified use of "we" in the consent agreement and FAQ, that the Principle Investigators are the only ones who will have access to the data. They would have to dig pretty far to notice that _"We are likely to release the full dataset by the end of 2019"_  in the [Frequently Asked Questions](https://iot-inspector.princeton.edu/blog/post/faq/#can-i-access-the-dataset). So it seems that a variety of approved researchers from a variety of institutions will have access to the data. This should be made more clear to users (research subjects).

**Comment by crazyideas21** [comment]
Thank you @nealmcb! We will address these issues in the next release!
