### ISSUE TITLE
Make IoT Inspector work on macOS Catalina

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#31]
The current version of IoT Inspector fails on macOS Catalina. @kumarde if you have a Catalina, could you run https://github.com/noise-lab/iot-inspector-client/blob/master/v2-src/deploy.sh on your Catalina and check in the updated binary (`dist/start_inspector_mac.zip`)? In that way, new users will be able to download the Catalina build.

(I can't do this because my macbook is stolen and I'm using Windows 10 now.)

**Comment by crazyideas21** [comment]
I can take care of this after mid-December. @kumarde

**Comment by ducalpha** [comment]
Is there any update on this issue? I have just updated to MacOS Catalina. Thanks!

**Comment by crazyideas21** [comment]
Not yet. Prioritizing over Windows release for now. Will work on this by the end of the month.
