### ISSUE TITLE
running without arp spoofing

### ISSUE THREAD

**Issue by ggmartins** [nyu-mlab/iot-inspector-client#47]
We're wondering here if there's a way to run in "router" mode, which is basically a linux with 2 interfaces forwarding traffic and with a NAT iptables rule (it sees all the traffic). If you give us directions we might be able to implement that feature in the code if it sounds interesting. Thanks!

**Comment by crazyideas21** [comment]
Possible, although this might involve some pretty significant changes to
the client code. I'd deprioritize this feature request.

**Comment by alexhaydock** [comment]
I am wondering this too - perhaps it would be easier to work in a mode whereby the software doesn't need to configure iptables and routing rules or ethernet interfaces, but could just simply "listen" on an interface.

Then it could be paired with a cheap smart switch offering port mirroring and then IoT devices can be monitored and investigated without compromising the integrity of the network through ARP spoofing, or increasing the complexity of the program through configuring forwarding etc.

**Comment by crazyideas21** [comment]
ARP spoofing is the only way we can think of to capture packets on-path without additional hardware. @alexhaydock

**Comment by crazyideas21** [comment]
@alexhaydock Also putting the wireless interface on promiscuous/monitor mode wouldn't give us the raw IP packets to/from various IoT devices.

**Comment by crazyideas21** [comment]
@alexhaydock For usability reasons, the team decides that IoT Inspector should be purely software based and shouldn't involve additional hardware -- not even ethernet cables.
