### ISSUE TITLE
404 Not Found running Ubuntu on Windows 10

### ISSUE THREAD

**Issue by arachmiel** [nyu-mlab/iot-inspector-client#5]
The IoT inspector was installed and is running on an Ubuntu instance on Windows 10 (installed form the Windows store).  

After running ~/princeton-iot-inspector/linux-start-inspector.sh I get:

Starting IoT Inspector...
WARNING: No route found for IPv6 destination :: (no default route?)
 * Serving Flask app "webserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:46241/ (Press CTRL+C to quit)
sysctl: setting key "net.ipv4.ip_forward": Invalid argument
net.ipv4.ip_forward = 1
127.0.0.1 - - [03/May/2019 14:43:08] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [03/May/2019 14:43:08] "GET /favicon.ico HTTP/1.1" 404 -

I have tried to access the page from my laptop and from my mobile but both show a 404 Not Found.

**Comment by crazyideas21** [comment]
Once you run `~/princeton-iot-inspector/linux-start-inspector.sh`, if you scroll to the bottom of the terminal window, do you see something like the following? Click on the link (like the one below) to view the inspection report.

![Screen Shot 2019-05-03 at 4 49 42 PM](https://user-images.githubusercontent.com/1479070/57164889-7d50ac00-6dc3-11e9-82c0-bf650e922b48.png)

**Comment by crazyideas21** [comment]
Also, if you don't see the screen above, try running `sudo -E ~/princeton-iot-inspector/linux-start-inspector.sh` and see if it helps?

**Comment by crazyideas21** [comment]
Another user emailed me the same issue when he ran IoT Inspector on Windows 10's Linux subsystem. Until we fix this issue, could you run on Linux for now, @arachmiel?

**Comment by crazyideas21** [comment]
Apparently, Windows Ubuntu subsystem may present the routing information differently than what we expected, causing the system to hang on this line: https://github.com/noise-lab/iot-inspector-client/blob/master/v2-src/utils.py#L140

For now, don't run it on Windows Ubuntu subsystem yet. Run it on Linux. I'll figure out how Windows presents the routing information and fix the code above.

**Comment by arachmiel** [comment]
Thanks for letting me know. I’ll give it a go on the Raspberry Pi until this is figured out.
