### ISSUE TITLE
Running Inspector as a service?

### ISSUE THREAD

**Issue by ghost** [nyu-mlab/iot-inspector-client#6]
Is it recommended to run Inspector as a service and if so, can you add the "run as a service" option to the installer?

**Comment by crazyideas21** [comment]
Will consider this option in the next release. Thanks for the suggestion!

**Comment by AnthonyMastrean** [comment]
systemd unit files seem quite a bit simpler than old sysv init scripts.

https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files

**Comment by pfletch101** [comment]
I currently have Inspector running as a systemd service on my Raspberry Pi. This required only minor code changes (basically just adding file output from the code that displays the monitoring URL). I am working on a few further tweaks to make it a little more 'systemd aware', but these should be done and tested on my system by the end of this week. I will submit them when I have tested them.
