### ISSUE TITLE
Inspector client required when accessing dashboard on web?

### ISSUE THREAD

**Issue by ghost** [nyu-mlab/iot-inspector-client#8]
Sometimes, i haven't determined when exactly, i get the message that i need the desktop client to see the dashboard on the web.

**Comment by crazyideas21** [comment]
When you opened links like this (below), did you see a message that asked you to run the desktop client?

![Screen Shot 2019-05-03 at 4 49 42 PM](https://user-images.githubusercontent.com/1479070/57180257-c4d34880-6e54-11e9-9083-5d30c836a6bd.png)
